stages:
  - build
  - deploy_gcp

build_images:
  stage:  build 
  image:  docker:20.10.16

  services:
    - docker:20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - docker login -u $FGN_DOCKUSR -p $FGN_DOCKPWD
  
  script:
    - docker build -t nalpsa/fgn-projeto-dio:1.0 app/.
    - docker push nalpsa/fgn-projeto-dio:1.0

deploy_gcp:

  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY
  
  script:
      - ssh -Oo StrictHostChecking=no -i $SSH_KEY gcp@$SSH_SERVER "rm -rf ./fgn-app-cicd-dio/ && git clone https://gitlab.com/fgnstudy/fgn-app-cicd-dio.git && cd fgn-app-cicd-dio && sudo chmod +x script.sh && ./script.sh" 
